name: Assignment Support Request
description: File an assignment support request, use this template only for the optional part of the labs.
title: "[Assignment]: "
labels: ["Assignment"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request support on the assignments!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this assignment support request?
      description: Please search to see if an issue already exists for this.
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: lab
    attributes:
      label: Lab
      description: What lab are you requesting support for?
      options:
        - Vector Add
        - Matrix Mult
        - DSPLib
        - Fir_Interconnect
        - Fir_Lowpass
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe which assignment you are requesting support for and what problems you are facing
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Anything else that you would like to include?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. If you are adding code, we suggest you use [code snippets](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).
    validations:
      required: false