name: Issue Report
description: File an issue report
title: "[Issue]: "
labels: ["Issue"]
assignees: [mariodruiz, vickyiii]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue with these labs!
  - type: checkboxes
    attributes:
      label: Is there an existing issue related to your problem?
      description: Please search to see if an issue already exists for this.
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: lab
    attributes:
      label: Lab
      description: What lab are you having issues with?
      options:
        - Vector Add 1
        - Vector Add 2
        - Matrix Mult
        - DSPLib
        - Fir_Lowpass
        - Fir_Interconnect
    validations:
      required: true
  - type: textarea
    id: section
    attributes:
      label: Section
      description: |
        Please describe in which section you are having problems

        Tip: Copy the section name directly from the lab instructions
      render: markdown
    validations:
      required: true
  - type: textarea
    id: step
    attributes:
      label: Step
      description: |
        Please describe in which step you are having problems

        Tip: Copy the step name and number directly from the lab instructions
      render: markdown
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the problem(s) you are facing
      render: markdown
    validations:
      required: true
  - type: textarea
    id: instance
    attributes:
      label: Instance
      description: |
        How and where are you running the tutorial?

        Tip: Cloud or on-premises
      render: markdown
    validations:
      required: false
  - type: textarea
    id: vitis
    attributes:
      label: Vitis
      description: |
        Please provide the Vitis version you are using

        Tip: On a terminal run `vitis --version`
      render: markdown
    validations:
      required: false
  - type: textarea
    id: xrt
    attributes:
      label: XRT
      description: |
        Please provide the XRT version you are using

        Tip: On a terminal run `xbutil --version`
      render: markdown
    validations:
      required: false
  - type: textarea
    id: platform
    attributes:
      label: Platform
      description: |
        Please provide the platform you are using
      render: markdown
    validations:
      required: false
  - type: textarea
    id: linux
    attributes:
      label: Linux distribution
      description: |
        Please provide the Linux distribution you are using

        Tip: On a terminal run `lsb_release -a`
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Anything else that you would like to include?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. If you are adding code, we suggest you use [code snippets](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).
    validations:
      required: false
